name: Docker Image CI

on:
  workflow_dispatch:

jobs:
 
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t unknownxyz/sample
    - name: login
      run: docker login -u unknownxyz -p garvatibot && docker push UnknownXYZ/sample
