name: Deploy to Heroku GANDU

on: 
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: 5hojib/heroku-deploy-action@v2
        with:
          heroku_api_key: 'HRKU-65fb6164-8938-4553-9f09-07e31f0d0e10'
          heroku_app_name: 'ocean476hj7'
          heroku_email: 'rajeshmandall123@outlook.com'
          team: 'suzie34544'
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
