name: Deploy to Heroku GANDU

on: 
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: 5hojib/heroku-deploy-action@v2
        with:
          heroku_api_key: 'HRKU-aa77b32c-4b3f-43d8-8b4b-fc914c3fabdc'
          heroku_app_name: 'ace728jsn'
          heroku_email: 'babyakculton.r.uyu1.54.1@gmail.com'
          team: 'suxs93839'
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
