name: Deploy to Heroku GANDU

on: 
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: 5hojib/heroku-deploy-action@v2
        with:
          heroku_api_key: 'HRKU-b9319cb6-6b60-4696-9365-ea35597fa780'
          heroku_app_name: 'ocean475gjv'
          heroku_email: 'rohitsharma32324@outlook.com'
          team: 'rohit45436'
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
