name: Deploy to Heroku GANDU

on: 
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: 5hojib/heroku-deploy-action@v2
        with:
          heroku_api_key: 'HRKU-81c2be9a-1756-4965-8c19-64a4320b1373'
          heroku_app_name: 'free628jsn'
          heroku_email: 'AnkitSingh34325@outlook.com'
          team: 'saaam32555'
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
