name: Deploy to Heroku GANDU

on: 
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: 5hojib/heroku-deploy-action@v2
        with:
          heroku_api_key: 'HRKU-b77ce64c-92d3-4f86-919d-ed8e8c191302'
          heroku_app_name: 'ace776ygh'
          heroku_email: 'diya.sonkar@outlook.com'
          team: 'sami34324'
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
